name: Testing

on:
  push:
    branches: [ "all" ]
  pull_request:
    branches: [ "all" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
